### ISSUE TITLE
Unable to fetch state for Charger

### ISSUE THREAD

**Issue by stepir** [cathiele/goecharger#14]
It started today and I have no clue why as I haven't changed anything, FW is still 0.41....

```
2022-11-06 20:39:48.401 ERROR (MainThread) [custom_components.goecharger] Unable to fetch state for Charger Garage
2022-11-06 20:39:48.402 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 970, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/goecharger/switch.py", line 122, in is_on
    return True if self.coordinator.data[self._chargername][self._attribute] == "on" else False
KeyError: 'Garage'
```

**Comment by stepir** [comment]
here with debug on

```
2022-11-06 20:45:44.608 DEBUG (MainThread) [custom_components.goecharger] async_setup
2022-11-06 20:45:44.608 DEBUG (MainThread) [custom_components.goecharger] [[OrderedDict([('name', 'Garage'), ('host', '192.168.2.217'), ('serial', '038266'), ('correction_factor', 1.1)])]]
2022-11-06 20:45:44.608 DEBUG (MainThread) [custom_components.goecharger] charger: 'Garage' host: '192.168.2.217'
2022-11-06 20:45:44.608 DEBUG (MainThread) [custom_components.goecharger] Updating status...
2022-11-06 20:45:44.608 DEBUG (MainThread) [custom_components.goecharger] update for 'Garage'..
2022-11-06 20:45:44.925 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom integration author for shelly using this method at custom_components/shelly/__init__.py, line 356: await self.hass.helpers.entity_registry.async_get_registry()
2022-11-06 20:45:44.929 ERROR (MainThread) [custom_components.goecharger] Unable to fetch state for Charger Garage
2022-11-06 20:45:44.930 DEBUG (MainThread) [custom_components.goecharger] Finished fetching goecharger data in 0.322 seconds (success: True)
2022-11-06 20:45:44.954 DEBUG (MainThread) [custom_components.goecharger.switch] setup_platform
2022-11-06 20:45:45.121 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform goecharger
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 970, in state
if (is_on := self.is_on) is None:
File "/config/custom_components/goecharger/switch.py", line 122, in is_on
return True if self.coordinator.data[self._chargername][self._attribute] == "on" else False
KeyError: 'Garage'
2022-11-06 20:45:45.124 ERROR (MainThread) [homeassistant.components.switch] Error while setting up goecharger platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 970, in state
if (is_on := self.is_on) is None:
File "/config/custom_components/goecharger/switch.py", line 122, in is_on
return True if self.coordinator.data[self._chargername][self._attribute] == "on" else False
KeyError: 'Garage'
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] setup_platform
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] charger name: 'Garage'
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] charger[0]: 'OrderedDict([('name', 'Garage'), ('host', '192.168.2.217'), ('serial', '038266'), ('correction_factor', 1.1)])'
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: car_status for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: charger_max_current for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: charger_absolute_max_current for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: charger_err for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: charger_access for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: stop_mode for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: cable_lock_mode for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: cable_max_current for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: pre_contactor_l1 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: pre_contactor_l2 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: pre_contactor_l3 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: post_contactor_l1 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: post_contactor_l2 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: post_contactor_l3 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: charger_temp for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: charger_temp0 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: charger_temp1 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: charger_temp2 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: charger_temp3 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: current_session_charged_energy for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: current_session_charged_energy_corrected for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: charge_limit for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: adapter for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: unlocked_by_card for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: energy_total for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: energy_total_corrected for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: wifi for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: u_l1 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: u_l2 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: u_l3 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: u_n for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: i_l1 for charger Garage
2022-11-06 20:45:53.939 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: i_l2 for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: i_l3 for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: p_l1 for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: p_l2 for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: p_l3 for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: p_n for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: p_all for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: lf_l1 for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: lf_l2 for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: lf_l3 for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: lf_n for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: firmware for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: serial_number for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: wifi_ssid for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: wifi_enabled for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: timezone_offset for charger Garage
2022-11-06 20:45:53.940 DEBUG (MainThread) [custom_components.goecharger.sensor] adding Sensor: timezone_dst_offset for charger Garage
```

**Comment by cathiele** [comment]
Can you tell me your plugin Version and also the home assistant version that you are using please?

**Comment by stepir** [comment]
> Can you tell me your plugin Version and also the home assistant version that you are using please?

hi @cathiele and sorry I should have included such info immediately:

plugin 0.25.2
Home Assistant 2022.10.5

**Comment by stepir** [comment]
closing the case as I found out it's my own router that decide to ignore the DHCP reservation for assigning a fixed ip to the charger!! sorry about it!
